version: '3'
services:
  srv-sync:
    build:
      context: .
      dockerfile: Dockerfile-sync
    container_name: app-sync
    volumes:
      - ./conf/settings.php:/opt/settings.php
      - ./conf/ConvertExcelToHTML.php:/opt/ConvertExcelToHTML.php
      - ./sync-dir:/sync-dir
      - ./public_html:/var/www/html
    environment:
      - STATE=0
      - HOST_FTP=${D9_FTP_HOST}
      - USER_FTP=${D9_FTP_USER}
      - PASS_FTP=${D9_FTP_PASS}
      - MYSQL_HOST=${D9_HOST}
      - MYSQL_PASS=${D9_PASS}
      - MYSQL_USER=${D9_USER}
      - MYSQL_DATABASE=${D9_DATABASE}
      - PATH_FILES=/var/www/html/sites/default/files
      - PATH_S3=${AWS_S3_BUCKET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_MYBUCKET=${AWS_MYBUCKET}
    command: /bin/bash -c "/sync-dir/sync.sh"
    depends_on:
      - srv-mysql-drupal
  srv-nginx-drupal:
    image: nginx:stable-alpine
    container_name: nginx-drupal9
    ports:
      - "80:80"
    volumes:
      - ./public_html:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/drupal.conf:/etc/nginx/conf.d/default.conf
      - ./conf/timeout.conf:/etc/nginx/conf.d/timeout.conf
    depends_on:
      - srv-mysql-drupal
  srv-mysql-drupal:
    image: mariadb:10.5
    container_name: "mysql-drupal9"
    ports:
      - "3301:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: XUcwQ46E
      MYSQL_DATABASE: local_db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./conf/db.sql:/docker-entrypoint-initdb.d/db.sql
  srv-php-drupal:
    build: .
    container_name: php-drupal9
    ports:
      - "9000:9000"
    volumes:
      - ./public_html:/var/www/html
      - ./conf/php.ini:/usr/local/etc/php/php.ini
      - ./sync-dir:/sync-dir
    depends_on:
      - srv-mysql-drupal
volumes:
  mysql-data:
